/* common configuration */
#define CONFIG_PWR_CTRL_ENABLED
#define CONFIG_SEARCH_ENABLED
#define CONFIG_OVERDRIVE_ENABLED
#define CONFIG_CRC16_ENABLED
#define CONFIG_CRC8_ALGO CRC8_TAB_32
#define CONFIG_CRC16_ALGO CRC16_TAB_32
#define CONFIG_ITERATION_RETRIES 1
#define CONFIG_BITBANG_TIMING TIMING_NULL

#if defined(T03)
# define CONFIG_MAX_SEARCH_FILTERS 5
#else
# define CONFIG_MAX_SEARCH_FILTERS 10
#endif
