name: ESP-IDF builds
env:
  ESPIDF_VER: v5.4
  ESP8266_SDK_VER: v3.4
  ESPIDF_DIR: /esp-idf
  ESP8266_SDK_DIR: /ESP8266_RTOS_SDK
  TOOLCHAIN_DIR: ~/.espressif
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
defaults:
  run:
    shell: bash
jobs:
  espidf_checkout:
    runs-on: ubuntu-latest
    container: ghcr.io/pstolarz/espidf-ci
    steps:
      - uses: actions/cache@v4
        with:
          path: |
            ${{ env.ESPIDF_DIR }}
            ${{ env.TOOLCHAIN_DIR }}
          key: espidf-${{ env.ESPIDF_VER }}
      - name: ESP IDF checkout
        run: |
          cd ${ESPIDF_DIR}
          if [ ! -f .CACHED ]; then
            git fetch || true
            git checkout -f ${ESPIDF_VER}
            git submodule update -f --init --recursive
            ./install.sh
            touch .CACHED
          fi
      - uses: actions/cache@v4
        with:
          path: |
            ${{ env.ESP8266_SDK_DIR }}
            ${{ env.TOOLCHAIN_DIR }}
          key: esp8266_rtos_sdk-${{ env.ESP8266_SDK_VER }}
      - name: ESP8266 RTOS SDK checkout
        run: |
          cd ${ESP8266_SDK_DIR}
          if [ ! -f .CACHED ]; then
            git fetch || true
            git checkout -f ${ESP8266_SDK_VER}
            git submodule update -f --init --recursive
            ./install.sh
            touch .CACHED
          fi
  espidf_info:
    runs-on: ubuntu-latest
    container: ghcr.io/pstolarz/espidf-ci
    needs: espidf_checkout
    steps:
      - uses: actions/cache@v4
        with:
          path: |
            ${{ env.ESPIDF_DIR }}
            ${{ env.TOOLCHAIN_DIR }}
          key: espidf-${{ env.ESPIDF_VER }}
      - name: ESP IDF recent versions info
        run: |
          cd ${ESPIDF_DIR}
          git fetch || true
          git tag | sort | awk "/$(git describe --tags)/ {f=1} f==1 {print}"
      - uses: actions/cache@v4
        with:
          path: |
            ${{ env.ESP8266_SDK_DIR }}
            ${{ env.TOOLCHAIN_DIR }}
          key: esp8266_rtos_sdk-${{ env.ESP8266_SDK_VER }}
      - name: ESP8266 RTOS SDK recent versions info
        run: |
          cd ${ESP8266_SDK_DIR}
          git fetch || true
          git tag | sort | awk "/$(git describe --tags)/ {f=1} f==1 {print}"
  espidf_build:
    runs-on: ubuntu-latest
    container: ghcr.io/pstolarz/espidf-ci
    needs: espidf_checkout
    strategy:
      matrix:
        plat:
          - esp32
          - esp32s2
          - esp32s3
          - esp32c2
          - esp32c3
          - esp32c6
          - esp32h2
          - esp32p4
          - esp8266
        example:
          - DallasTemperature
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        if: ${{ matrix.plat }} != 'esp8266'
        with:
          path: |
            ${{ env.ESPIDF_DIR }}
            ${{ env.TOOLCHAIN_DIR }}
          key: espidf-${{ env.ESPIDF_VER }}
      - uses: actions/cache@v4
        if: ${{ matrix.plat }} == 'esp8266'
        with:
          path: |
            ${{ env.ESP8266_SDK_DIR }}
            ${{ env.TOOLCHAIN_DIR }}
          key: esp8266_rtos_sdk-${{ env.ESP8266_SDK_VER }}
      - name: Build
        run: |
          repo_dir=$(pwd)
          rm -rf /tmp/espidf-build && mkdir /tmp/espidf-build && cd /tmp/espidf-build
          mkdir components
          ln -s ${repo_dir} components/OneWireNg
          ln -s ${repo_dir}/examples/esp-idf/${{ matrix.example }}/main main
          ln -s ${repo_dir}/examples/esp-idf/${{ matrix.example }}/CMakeLists.txt CMakeLists.txt
          echo "CONFIG_PWR_CTRL_ENABLED=y"      >sdkconfig.defaults
          echo "CONFIG_OVERDRIVE_ENABLED=y"     >>sdkconfig.defaults
          echo "CONFIG_CRC8_ALGO_TAB_32=y"      >>sdkconfig.defaults
          echo "CONFIG_CRC16_ENABLED=y"         >>sdkconfig.defaults
          echo "CONFIG_CRC16_ALGO_BASIC=y"      >>sdkconfig.defaults
          echo "CONFIG_BUS_BLINK_PROTECTION=y"  >>sdkconfig.defaults
          echo "CONFIG_ITERATION_RETRIES=1"     >>sdkconfig.defaults
          if [[ "${{ matrix.plat }}" != 'esp8266' ]]; then
            source ${ESPIDF_DIR}/export.sh
            idf.py --preview set-target ${{ matrix.plat }}
            idf.py build
          else
            source ${ESP8266_SDK_DIR}/export.sh
            idf.py build
          fi
